GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Saphira Bjartskular",
    "username": "uniquename",
    "password": "bighungrydog"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ba",
  "name": "Should be rejected",
  "password": "newpassword"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "bakrutch",
  "name": "Should be rejected",
  "password": "ba"
}